name: Docker

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./bullseye/Dockerfile
            tag: "latest"
          - dockerfile: ./bullseye/Dockerfile
            tag: "bullseye"
          - dockerfile: ./bullseye/Dockerfile.slim
            tag: "bullseye-slim"
          - dockerfile: ./buster/Dockerfile
            tag: "buster"
          - dockerfile: ./buster/Dockerfile.slim
            tag: "buster-slim"
          - dockerfile: ./jessie/Dockerfile
            tag: "jessie"
          - dockerfile: ./jessie/Dockerfile.slim
            tag: "jessie-slim"
          - dockerfile: ./sid/Dockerfile
            tag: "sid"
          - dockerfile: ./sid/Dockerfile.slim
            tag: "sid-slim"
          - dockerfile: ./buster/Dockerfile
            tag: "stretch"
          - dockerfile: ./buster/Dockerfile.slim
            tag: "stretch-slim"
          - dockerfile: ./wheezy/Dockerfile
            tag: "wheezy"
          - dockerfile: ./wheezy/Dockerfile.slim
            tag: "wheezy-slim"

      fail-fast: false

    name: Docker (dockette/debian:${{ matrix.tag }})

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: dockette/debian:${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64
