name: "Docker"

on:
  push:
    branches: ["master"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    name: "Build"
    uses: dockette/.github/.github/workflows/docker.yml@master
    secrets: inherit
    with:
        image: "dockette/debian"
        tag: "${{ matrix.tag }}"
        dockerfile: "${{ matrix.dockerfile }}"
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        include:
          # latest
          - dockerfile: bullseye/Dockerfile
            tag: latest
          # 12
          - dockerfile: bookworm/Dockerfile
            tag: bookworm
          - dockerfile: bookworm/Dockerfile.slim
            tag: bookworm-slim
          # 11
          - dockerfile: bullseye/Dockerfile
            tag: bullseye
          - dockerfile: bullseye/Dockerfile.slim
            tag: bullseye-slim
          # 10
          - dockerfile: buster/Dockerfile
            tag: buster
          - dockerfile: buster/Dockerfile.slim
            tag: buster-slim
          # 9
          - dockerfile: stretch/Dockerfile
            tag: stretch
          - dockerfile: stretch/Dockerfile.slim
            tag: stretch-slim

